export const SEARCH_SINGLE_LIGHT = 'SEARCH_SINGLE_LIGHT'
export const CHANGE_SEARCH_VALUE = 'CHANGE_SEARCH_VALUE'
export const SET_LIST_LOADING = 'SET_LIST_LOADING'
export const CHANGE_LIGHT_SWITCH = 'CHANGE_LIGHT_SWITCH'